# EPBT - SAP Enterprise Portal Behavior Testing
# http://github.com/arnaud/EPBT  -  MIT License

#
# Configuration
#
config:
  portal:
    root_url: http://srm.tatamotors.com/irj/portal
    valid_credential:
      name: user_01
      password: abcd1234
  watir:
    browser: ie
    #speed: fast
    maximize: false
    #bring_to_front: true
  report:
    dir: reports
    screenshots:
      after: each failed step
      dir: screens
