# Totori - User Acceptance Testing Workbench
# http://github.com/arnaud/totori - MIT License

#
# Rake tasks
#

require 'rubygems'
require 'cucumber/rake/task'
require 'ftools'
#require 'launchy'

# create report directories
FileUtils.mkdir_p 'reports/screens'

# generate the report name
def report_filename
  "reports/report_#{Time.now.strftime("%Y%m%d-%H%M%S")}.html"
end

# run my own features, output in the console
Cucumber::Rake::Task.new(:run) do |t|
  t.cucumber_opts = "--tags ~@example --format pretty"
end

# run all my features, output in an html report file
Cucumber::Rake::Task.new(:runreport) do |t|
  t.cucumber_opts = "--tags ~@example --format TotoriFormatter --out #{report_filename}"
  #File.new(report_filename, "w")
  #Launchy.open("#{Dir.pwd}/#{report_filename}")
end

## run a specific own features, output in an html report file
#task :runfeature, :feature do |t, args|
#  
#end
#
##Cucumber::Rake::Task.new(:runfeature) do |t|
#  puts t.profile
#  exit
#  t.cucumber_opts = "features/#{arg}.feature --format TotoriFormatter --out #{report_filename}"
#  #File.new(report_filename, "w")
#  #Launchy.open("#{Dir.pwd}/#{report_filename}")
#end

# run the example features
Cucumber::Rake::Task.new(:example) do |t|
  t.cucumber_opts = "--tags @example --format TotoriFormatter --out #{report_filename}"
  #File.new(report_filename, "w")
  #Launchy.open("#{Dir.pwd}/#{report_filename}")
end
